# Generated by Django 3.0.7 on 2020-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontosturisticus_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticus',
            name='Comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
