# Generated by Django 3.0.7 on 2020-06-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_auto_20200612_1151'),
        ('core', '0005_pontosturisticus_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticus',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
            preserve_default=False,
        ),
    ]
