# Generated by Django 3.0.7 on 2020-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200613_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticus',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Pontos_turisticos'),
        ),
    ]
