# Generated by Django 3.0.7 on 2020-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='linha2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
